import type { Metadata } from 'next'

import localFont from 'next/font/local'
// import { Provider } from 'react-redux'

import { store } from './store'
import { AuthProvider } from '../widgets/auth/AuthProvider'
import { ThemeProvider } from '@/components/ui/theme-provider'
import './globals.css'
import { Providers } from './providers'

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff2',
//   variable: '--font-geist-sans',
//   weight: '100 900'
// });

// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff2',
//   variable: '--font-geist-mono',
//   weight: '100 900'
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
// export default function RootLayout({
//   children
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html suppressHydrationWarning>
//       <body className="min-h-screen bg-background font-sans antialiased" suppressHydrationWarning>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   )
// }
