import { TranscriptProbeError } from './youtube-utils'

export type CaptionKind = 'manual' | 'asr'

export interface CaptionTrack {
  languageCode: string
  baseUrl: string
  kind?: string
  vssId?: string
}

export interface SelectCaptionTrackOptions {
  lang: string
  includeAutoGenerated: boolean
}

export interface SelectedCaptionTrack {
  track: CaptionTrack
  captionKind: CaptionKind
  resolvedLang: string
}

export function isAsrTrack(track: CaptionTrack): boolean {
  return track.kind === 'asr' || track.vssId?.startsWith('a.') === true
}

export function languageMatches(
  trackLanguage: string,
  requestedLanguage: string
): boolean {
  const track = trackLanguage.toLowerCase()
  const requested = requestedLanguage.toLowerCase()

  if (track === requested) return true
  if (track.startsWith(`${requested}-`)) return true
  if (requested.startsWith(`${track}-`)) return true

  return false
}

export function selectCaptionTrack(
  tracks: CaptionTrack[],
  options: SelectCaptionTrackOptions
): SelectedCaptionTrack {
  const { lang, includeAutoGenerated } = options

  if (tracks.length === 0) {
    throw new TranscriptProbeError(
      'Transcript is disabled on this video.',
      'CAPTIONS_DISABLED'
    )
  }

  const matching = tracks.filter((track) =>
    languageMatches(track.languageCode, lang)
  )

  const manual = matching.find((track) => !isAsrTrack(track))
  if (manual) {
    return {
      track: manual,
      captionKind: 'manual',
      resolvedLang: manual.languageCode
    }
  }

  const asr = matching.find((track) => isAsrTrack(track))
  if (asr) {
    if (!includeAutoGenerated) {
      throw new TranscriptProbeError(
        `Only auto-generated captions are available for ${lang}. Enable ASR fallback to fetch them.`,
        'NO_TRANSCRIPT'
      )
    }

    return {
      track: asr,
      captionKind: 'asr',
      resolvedLang: asr.languageCode
    }
  }

  const available = [...new Set(tracks.map((track) => track.languageCode))]
  const asrAvailable = tracks
    .filter(isAsrTrack)
    .map((track) => track.languageCode)

  throw new TranscriptProbeError(
    `No captions in ${lang}. Available: ${available.join(', ')}` +
      (asrAvailable.length > 0
        ? ` (auto-generated: ${[...new Set(asrAvailable)].join(', ')})`
        : ''),
    'NO_TRANSCRIPT'
  )
}
