import {
  isAsrTrack,
  languageMatches,
  selectCaptionTrack,
  type CaptionKind,
  type CaptionTrack
} from './caption-track-selector'
import { TranscriptProbeError } from './youtube-utils'

const INNERTUBE_API_URL =
  'https://www.youtube.com/youtubei/v1/player?prettyPrint=false'

const WEB_USER_AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'

const INNERTUBE_CLIENTS = [
  {
    clientName: 'ANDROID',
    clientVersion: '20.10.38',
    userAgent: 'com.google.android.youtube/20.10.38 (Linux; U; Android 14) gzip'
  },
  {
    clientName: 'WEB',
    clientVersion: '2.20260301.01.00',
    userAgent: WEB_USER_AGENT
  },
  {
    clientName: 'MWEB',
    clientVersion: '2.20260301.01.00',
    userAgent:
      'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15'
  }
] as const

const RE_XML_TRANSCRIPT = /<text start="([^"]*)" dur="([^"]*)">([^<]*)<\/text>/g

export interface TranscriptSegment {
  text: string
  duration: number
  offset: number
}

export interface FetchYoutubeCaptionsOptions {
  lang: string
  includeAutoGenerated?: boolean
}

export interface FetchYoutubeCaptionsResult {
  segments: TranscriptSegment[]
  captionKind: CaptionKind
  resolvedLang: string
}

function parseCaptionTracksFromPlayerResponse(
  playerResponse: unknown
): CaptionTrack[] {
  const tracks = (
    playerResponse as {
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: Array<{
            languageCode?: string
            baseUrl?: string
            kind?: string
            vssId?: string
          }>
        }
      }
    }
  )?.captions?.playerCaptionsTracklistRenderer?.captionTracks

  if (!Array.isArray(tracks)) return []

  return tracks
    .filter((track): track is CaptionTrack =>
      Boolean(track.languageCode && track.baseUrl)
    )
    .map((track) => ({
      languageCode: track.languageCode!,
      baseUrl: track.baseUrl!,
      kind: track.kind,
      vssId: track.vssId
    }))
}

function parseInlineJson(html: string, globalName: string): unknown | null {
  const startToken = `var ${globalName} = `
  const startIndex = html.indexOf(startToken)
  if (startIndex === -1) return null

  const jsonStart = startIndex + startToken.length
  let depth = 0

  for (let i = jsonStart; i < html.length; i++) {
    if (html[i] === '{') depth++
    else if (html[i] === '}') {
      depth--
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(jsonStart, i + 1))
        } catch {
          return null
        }
      }
    }
  }

  return null
}

function mergeCaptionTracks(trackGroups: CaptionTrack[][]): CaptionTrack[] {
  const merged = new Map<string, CaptionTrack>()

  for (const tracks of trackGroups) {
    for (const track of tracks) {
      const key =
        track.vssId ?? `${track.languageCode}:${track.kind ?? 'manual'}`
      if (!merged.has(key)) {
        merged.set(key, track)
      }
    }
  }

  return [...merged.values()]
}

async function fetchCaptionTracksViaInnerTube(
  videoId: string
): Promise<CaptionTrack[]> {
  const groups: CaptionTrack[][] = []

  for (const client of INNERTUBE_CLIENTS) {
    try {
      const response = await fetch(INNERTUBE_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': client.userAgent
        },
        body: JSON.stringify({
          context: {
            client: {
              clientName: client.clientName,
              clientVersion: client.clientVersion
            }
          },
          videoId
        }),
        cache: 'no-store'
      })

      if (!response.ok) continue

      const data = await response.json()
      const tracks = parseCaptionTracksFromPlayerResponse(data)
      if (tracks.length > 0) {
        groups.push(tracks)
      }
    } catch {
      // try next client
    }
  }

  return mergeCaptionTracks(groups)
}

async function fetchCaptionTracksViaWebPage(
  videoId: string,
  lang: string
): Promise<CaptionTrack[]> {
  const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: {
      'User-Agent': WEB_USER_AGENT,
      'Accept-Language': lang
    },
    cache: 'no-store'
  })

  if (!response.ok) {
    throw new TranscriptProbeError(
      `YouTube watch page HTTP ${response.status}`,
      'FETCH_FAILED'
    )
  }

  const html = await response.text()

  if (html.includes('class="g-recaptcha"')) {
    throw new TranscriptProbeError(
      'YouTube requires captcha from this host',
      'FETCH_FAILED'
    )
  }

  const playerResponse = parseInlineJson(html, 'ytInitialPlayerResponse')
  return parseCaptionTracksFromPlayerResponse(playerResponse)
}

async function listCaptionTracks(
  videoId: string,
  lang: string
): Promise<CaptionTrack[]> {
  const innerTubeTracks = await fetchCaptionTracksViaInnerTube(videoId)
  if (innerTubeTracks.length > 0) {
    return innerTubeTracks
  }

  return fetchCaptionTracksViaWebPage(videoId, lang)
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) =>
      String.fromCodePoint(parseInt(hex, 16))
    )
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
}

function parseTranscriptXml(xml: string): TranscriptSegment[] {
  const srv3Results: TranscriptSegment[] = []
  const pRegex = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g
  let match: RegExpExecArray | null

  while ((match = pRegex.exec(xml)) !== null) {
    const startMs = parseInt(match[1], 10)
    const durMs = parseInt(match[2], 10)
    const inner = match[3]
    let text = ''
    const sRegex = /<s[^>]*>([^<]*)<\/s>/g
    let sMatch: RegExpExecArray | null

    while ((sMatch = sRegex.exec(inner)) !== null) {
      text += sMatch[1]
    }

    if (!text) {
      text = inner.replace(/<[^>]+>/g, '')
    }

    text = decodeEntities(text).trim()
    if (text) {
      srv3Results.push({
        text,
        duration: durMs,
        offset: startMs
      })
    }
  }

  if (srv3Results.length > 0) return srv3Results

  return [...xml.matchAll(RE_XML_TRANSCRIPT)].map((result) => ({
    text: decodeEntities(result[3]),
    duration: parseFloat(result[2]),
    offset: parseFloat(result[1])
  }))
}

function assertYoutubeCaptionUrl(url: string, videoId: string): URL {
  let captionUrl: URL

  try {
    captionUrl = new URL(url)
  } catch {
    throw new TranscriptProbeError(
      'Invalid caption URL from YouTube',
      'FETCH_FAILED'
    )
  }

  if (!captionUrl.hostname.endsWith('youtube.com')) {
    throw new TranscriptProbeError(
      `Caption URL host not allowed for ${videoId}`,
      'FETCH_FAILED'
    )
  }

  return captionUrl
}

async function fetchTranscriptXml(
  track: CaptionTrack,
  videoId: string,
  lang: string
): Promise<string> {
  const captionUrl = assertYoutubeCaptionUrl(track.baseUrl, videoId)

  const response = await fetch(captionUrl.toString(), {
    headers: {
      'User-Agent': WEB_USER_AGENT,
      'Accept-Language': lang
    },
    cache: 'no-store'
  })

  if (!response.ok) {
    throw new TranscriptProbeError(
      `Caption download HTTP ${response.status}`,
      'FETCH_FAILED'
    )
  }

  return response.text()
}

export async function fetchYoutubeCaptions(
  videoId: string,
  options: FetchYoutubeCaptionsOptions
): Promise<FetchYoutubeCaptionsResult> {
  const includeAutoGenerated = options.includeAutoGenerated ?? true
  const tracks = await listCaptionTracks(videoId, options.lang)
  const selected = selectCaptionTrack(tracks, {
    lang: options.lang,
    includeAutoGenerated
  })

  let xml = await fetchTranscriptXml(
    selected.track,
    videoId,
    selected.resolvedLang
  )
  let segments = parseTranscriptXml(xml)

  if (
    segments.length === 0 &&
    isAsrFallbackCandidate(selected.track, tracks, options.lang)
  ) {
    const asrTrack = tracks.find(
      (track) =>
        isAsrTrack(track) && languageMatches(track.languageCode, options.lang)
    )

    if (asrTrack && asrTrack.baseUrl !== selected.track.baseUrl) {
      xml = await fetchTranscriptXml(asrTrack, videoId, asrTrack.languageCode)
      segments = parseTranscriptXml(xml)
      if (segments.length > 0) {
        return {
          segments,
          captionKind: 'asr',
          resolvedLang: asrTrack.languageCode
        }
      }
    }
  }

  if (segments.length === 0) {
    throw new TranscriptProbeError(
      'Caption track returned empty transcript.',
      'NO_TRANSCRIPT'
    )
  }

  return {
    segments,
    captionKind: selected.captionKind,
    resolvedLang: selected.resolvedLang
  }
}

function isAsrFallbackCandidate(
  selected: CaptionTrack,
  tracks: CaptionTrack[],
  lang: string
): boolean {
  return (
    !isAsrTrack(selected) &&
    tracks.some(
      (track) => isAsrTrack(track) && languageMatches(track.languageCode, lang)
    )
  )
}
