import {
  isAsrTrack,
  languageMatches,
  selectCaptionTrack,
  type CaptionKind,
  type CaptionTrack
} from './caption-track-selector'
import { TranscriptProbeError } from './youtube-utils'

const INNERTUBE_PLAYER_URL =
  'https://www.youtube.com/youtubei/v1/player?prettyPrint=false'

const WEB_USER_AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'

const ANDROID_USER_AGENT =
  'com.google.android.youtube/20.10.38 (Linux; U; Android 14) gzip'

const CONSENT_COOKIE = 'CONSENT=YES+cb; PREF=f6=40000000&hl=en'

const INNERTUBE_CLIENTS = [
  {
    clientName: 'ANDROID',
    clientVersion: '20.10.38',
    userAgent: ANDROID_USER_AGENT
  },
  {
    clientName: 'IOS',
    clientVersion: '20.10.4',
    userAgent:
      'com.google.ios.youtube/20.10.4 (iPhone14,3; U; CPU iOS 17_0 like Mac OS X)'
  }
] as const

const RE_XML_TRANSCRIPT = /<text start="([^"]*)" dur="([^"]*)">([^<]*)<\/text>/g

export interface TranscriptSegment {
  text: string
  duration: number
  offset: number
}

export interface FetchYoutubeCaptionsOptions {
  lang: string
  includeAutoGenerated?: boolean
}

export interface FetchYoutubeCaptionsResult {
  segments: TranscriptSegment[]
  captionKind: CaptionKind
  resolvedLang: string
}

interface YouTubeSession {
  tracks: CaptionTrack[]
  captchaDetected: boolean
}

function parseCaptionTracksFromPlayerResponse(
  playerResponse: unknown
): CaptionTrack[] {
  const tracks = (
    playerResponse as {
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: Array<{
            languageCode?: string
            baseUrl?: string
            kind?: string
            vssId?: string
          }>
        }
      }
    }
  )?.captions?.playerCaptionsTracklistRenderer?.captionTracks

  if (!Array.isArray(tracks)) return []

  return tracks
    .filter((track): track is CaptionTrack =>
      Boolean(track.languageCode && track.baseUrl)
    )
    .map((track) => ({
      languageCode: track.languageCode!,
      baseUrl: track.baseUrl!,
      kind: track.kind,
      vssId: track.vssId
    }))
}

function parseInlineJson(html: string, globalName: string): unknown | null {
  const startToken = `var ${globalName} = `
  const startIndex = html.indexOf(startToken)
  if (startIndex === -1) return null

  const jsonStart = startIndex + startToken.length
  let depth = 0

  for (let i = jsonStart; i < html.length; i++) {
    if (html[i] === '{') depth++
    else if (html[i] === '}') {
      depth--
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(jsonStart, i + 1))
        } catch {
          return null
        }
      }
    }
  }

  return null
}

function trackNeedsPoToken(track: CaptionTrack): boolean {
  return track.baseUrl.includes('exp=xpe')
}

function isBetterTrack(
  candidate: CaptionTrack,
  current: CaptionTrack
): boolean {
  const candidateNeedsPo = trackNeedsPoToken(candidate)
  const currentNeedsPo = trackNeedsPoToken(current)

  if (currentNeedsPo && !candidateNeedsPo) return true
  if (!currentNeedsPo && candidateNeedsPo) return false

  return false
}

function mergeCaptionTracks(trackGroups: CaptionTrack[][]): CaptionTrack[] {
  const merged = new Map<string, CaptionTrack>()

  for (const tracks of trackGroups) {
    for (const track of tracks) {
      const key =
        track.vssId ?? `${track.languageCode}:${track.kind ?? 'manual'}`
      const existing = merged.get(key)

      if (!existing || isBetterTrack(track, existing)) {
        merged.set(key, track)
      }
    }
  }

  return [...merged.values()]
}

async function fetchWatchPageSession(
  videoId: string,
  lang: string
): Promise<YouTubeSession> {
  const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: {
      'User-Agent': WEB_USER_AGENT,
      'Accept-Language': `${lang},en-US;q=0.9,en;q=0.8`,
      Cookie: CONSENT_COOKIE,
      Referer: 'https://www.youtube.com/'
    },
    cache: 'no-store'
  })

  if (!response.ok) {
    throw new TranscriptProbeError(
      `YouTube watch page HTTP ${response.status}`,
      'FETCH_FAILED'
    )
  }

  const html = await response.text()
  const captchaDetected = html.includes('class="g-recaptcha"')
  const playerResponse = parseInlineJson(html, 'ytInitialPlayerResponse')

  return {
    tracks: parseCaptionTracksFromPlayerResponse(playerResponse),
    captchaDetected
  }
}

async function fetchCaptionTracksViaInnerTube(
  videoId: string
): Promise<CaptionTrack[]> {
  const groups: CaptionTrack[][] = []

  for (const client of INNERTUBE_CLIENTS) {
    try {
      const response = await fetch(INNERTUBE_PLAYER_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': client.userAgent,
          Cookie: CONSENT_COOKIE
        },
        body: JSON.stringify({
          context: {
            client: {
              clientName: client.clientName,
              clientVersion: client.clientVersion
            }
          },
          videoId
        }),
        cache: 'no-store'
      })

      if (!response.ok) continue

      const data = await response.json()
      const tracks = parseCaptionTracksFromPlayerResponse(data)
      if (tracks.length > 0) {
        groups.push(tracks)
      }
    } catch {
      // try next client
    }
  }

  return mergeCaptionTracks(groups)
}

async function listCaptionTracks(
  videoId: string,
  lang: string
): Promise<CaptionTrack[]> {
  const [watchSession, innerTubeTracks] = await Promise.all([
    fetchWatchPageSession(videoId, lang),
    fetchCaptionTracksViaInnerTube(videoId)
  ])

  if (watchSession.captchaDetected) {
    throw new TranscriptProbeError(
      'YouTube blocked this server IP (captcha required). Configure SUPADATA_API_KEY or use a residential proxy.',
      'HOST_BLOCKED'
    )
  }

  const tracks = mergeCaptionTracks([innerTubeTracks, watchSession.tracks])

  if (tracks.length === 0) {
    throw new TranscriptProbeError(
      'YouTube returned no caption tracks from this host. Datacenter IPs (Render/Vercel/AWS) are often blocked — configure SUPADATA_API_KEY as fallback.',
      'HOST_BLOCKED'
    )
  }

  return tracks
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) =>
      String.fromCodePoint(parseInt(hex, 16))
    )
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
}

function parseTranscriptXml(xml: string): TranscriptSegment[] {
  const srv3Results: TranscriptSegment[] = []
  const pRegex = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g
  let match: RegExpExecArray | null

  while ((match = pRegex.exec(xml)) !== null) {
    const startMs = parseInt(match[1], 10)
    const durMs = parseInt(match[2], 10)
    const inner = match[3]
    let text = ''
    const sRegex = /<s[^>]*>([^<]*)<\/s>/g
    let sMatch: RegExpExecArray | null

    while ((sMatch = sRegex.exec(inner)) !== null) {
      text += sMatch[1]
    }

    if (!text) {
      text = inner.replace(/<[^>]+>/g, '')
    }

    text = decodeEntities(text).trim()
    if (text) {
      srv3Results.push({
        text,
        duration: durMs,
        offset: startMs
      })
    }
  }

  if (srv3Results.length > 0) return srv3Results

  return [...xml.matchAll(RE_XML_TRANSCRIPT)].map((result) => ({
    text: decodeEntities(result[3]),
    duration: parseFloat(result[2]),
    offset: parseFloat(result[1])
  }))
}

function assertYoutubeCaptionUrl(url: string, videoId: string): URL {
  let captionUrl: URL

  try {
    captionUrl = new URL(url)
  } catch {
    throw new TranscriptProbeError(
      'Invalid caption URL from YouTube',
      'FETCH_FAILED'
    )
  }

  if (!captionUrl.hostname.endsWith('youtube.com')) {
    throw new TranscriptProbeError(
      `Caption URL host not allowed for ${videoId}`,
      'FETCH_FAILED'
    )
  }

  return captionUrl
}

async function fetchTranscriptXml(
  track: CaptionTrack,
  videoId: string,
  lang: string
): Promise<string> {
  const captionUrl = assertYoutubeCaptionUrl(track.baseUrl, videoId)

  const response = await fetch(captionUrl.toString(), {
    headers: {
      'User-Agent': WEB_USER_AGENT,
      'Accept-Language': lang,
      Cookie: CONSENT_COOKIE,
      Referer: `https://www.youtube.com/watch?v=${videoId}`
    },
    cache: 'no-store'
  })

  if (!response.ok) {
    throw new TranscriptProbeError(
      `Caption download HTTP ${response.status}`,
      'FETCH_FAILED'
    )
  }

  const body = await response.text()

  if (!body.trim()) {
    throw new TranscriptProbeError(
      'YouTube returned an empty caption payload (PoToken required for this track).',
      'FETCH_FAILED'
    )
  }

  return body
}

export async function fetchYoutubeCaptions(
  videoId: string,
  options: FetchYoutubeCaptionsOptions
): Promise<FetchYoutubeCaptionsResult> {
  const includeAutoGenerated = options.includeAutoGenerated ?? true
  const tracks = await listCaptionTracks(videoId, options.lang)
  const selected = selectCaptionTrack(tracks, {
    lang: options.lang,
    includeAutoGenerated
  })

  let xml = await fetchTranscriptXml(
    selected.track,
    videoId,
    selected.resolvedLang
  )
  let segments = parseTranscriptXml(xml)

  if (
    segments.length === 0 &&
    isAsrFallbackCandidate(selected.track, tracks, options.lang)
  ) {
    const asrTrack = tracks.find(
      (track) =>
        isAsrTrack(track) && languageMatches(track.languageCode, options.lang)
    )

    if (asrTrack && asrTrack.baseUrl !== selected.track.baseUrl) {
      xml = await fetchTranscriptXml(asrTrack, videoId, asrTrack.languageCode)
      segments = parseTranscriptXml(xml)
      if (segments.length > 0) {
        return {
          segments,
          captionKind: 'asr',
          resolvedLang: asrTrack.languageCode
        }
      }
    }
  }

  if (segments.length === 0) {
    throw new TranscriptProbeError(
      'Caption track returned empty transcript.',
      'NO_TRANSCRIPT'
    )
  }

  return {
    segments,
    captionKind: selected.captionKind,
    resolvedLang: selected.resolvedLang
  }
}

function isAsrFallbackCandidate(
  selected: CaptionTrack,
  tracks: CaptionTrack[],
  lang: string
): boolean {
  return (
    !isAsrTrack(selected) &&
    tracks.some(
      (track) => isAsrTrack(track) && languageMatches(track.languageCode, lang)
    )
  )
}
