// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "auth": {
    "register": {
      "title": "Create your account",
      "success": {
        "title": "Success",
        "description": "Account created successfully! Please log in."
      },
      "error": {
        "title": "Error",
        "description": "Registration failed",
        "validation": {
          "required": "This field is required",
          "email": "Please enter a valid email",
          "password": {
            "min": "Password must be at least {length} characters",
            "match": "Passwords must match"
          }
        }
      },
      "fields": {
        "username": "Username",
        "email": "Email",
        "password": "Password",
        "confirmPassword": "Confirm Password"
      },
      "buttons": {
        "submit": "Register",
        "switchToLogin": "Already have an account? Log in"
      }
    }
  },
  "Index": {
    "title": "File sharing platform",
    "description": "Share your files securely and easily"
  }
};
export default messages;