import { describe, it, expect } from 'vitest'

import {
  isAsrTrack,
  languageMatches,
  selectCaptionTrack,
  type CaptionTrack
} from '@/infrastructure/transcript/caption-track-selector'

const manualEn: CaptionTrack = {
  languageCode: 'en',
  baseUrl: 'https://www.youtube.com/api/timedtext?v=1',
  vssId: '.en'
}

const asrEn: CaptionTrack = {
  languageCode: 'en',
  baseUrl: 'https://www.youtube.com/api/timedtext?v=2',
  kind: 'asr',
  vssId: 'a.en'
}

const asrFr: CaptionTrack = {
  languageCode: 'fr',
  baseUrl: 'https://www.youtube.com/api/timedtext?v=3',
  kind: 'asr',
  vssId: 'a.fr'
}

describe('caption-track-selector', () => {
  it('detects ASR tracks by kind or vssId', () => {
    expect(isAsrTrack(asrEn)).toBe(true)
    expect(isAsrTrack(manualEn)).toBe(false)
  })

  it('matches language prefixes', () => {
    expect(languageMatches('fr-FR', 'fr')).toBe(true)
    expect(languageMatches('de', 'de-DE')).toBe(true)
    expect(languageMatches('en', 'fr')).toBe(false)
  })

  it('prefers manual captions over ASR for the same language', () => {
    const selected = selectCaptionTrack([asrEn, manualEn], {
      lang: 'en',
      includeAutoGenerated: true
    })

    expect(selected.captionKind).toBe('manual')
    expect(selected.track.vssId).toBe('.en')
  })

  it('falls back to ASR when manual captions are missing', () => {
    const selected = selectCaptionTrack([asrEn], {
      lang: 'en',
      includeAutoGenerated: true
    })

    expect(selected.captionKind).toBe('asr')
    expect(selected.resolvedLang).toBe('en')
  })

  it('rejects ASR-only tracks when auto-generated fallback is disabled', () => {
    expect(() =>
      selectCaptionTrack([asrFr], {
        lang: 'fr',
        includeAutoGenerated: false
      })
    ).toThrow(/auto-generated captions are available/)
  })
})
